stages:
  - build

build-debian-package:
  stage: build
  image: debian:latest
  script:
    - apt-get update && apt-get install -y build-essential
    - dpkg-buildpackage -b -us -uc
    - ls -l 
    - ls -l ../
